spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/prueba
    username: facundo
    password: 152233
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update